[build]
  base = "frontend/"
  publish = "build/"
  command = "yarn build"

[build.environment]
  NODE_VERSION = "20"
  REACT_APP_BACKEND_URL = "https://your-backend-url.vercel.app"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.vercel.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200