services:
  - type: web
    name: cred-app
    env: docker
    dockerfilePath: ./Dockerfile
    disk:
      name: cred-disk
      mountPath: /app/uploads
      sizeGB: 1
    envVars:
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: cred_database
      - key: JWT_SECRET
        generateValue: true
      - key: SMTP_SERVER
        sync: false
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USERNAME
        sync: false  
      - key: SMTP_PASSWORD
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: CONTACT_PHONE_NUMBER
        sync: false

databases:
  - name: cred-mongodb
    databaseName: cred_database